name: Download google drive data and push to core-curriculum/data

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Download google sheets and push to core-curriculum/data
    runs-on: ubuntu-latest
    env:
      GAUTH_TYPE: ${{secrets.GAUTH_TYPE}}
      GAUTH_PROJECT_ID: ${{secrets.GAUTH_PROJECT_ID}}
      GAUTH_PRIVATE_KEY_ID: ${{secrets.GAUTH_PRIVATE_KEY_ID}}
      GAUTH_PRIVATE_KEY: ${{secrets.GAUTH_PRIVATE_KEY}}
      GAUTH_CLIENT_EMAIL: ${{secrets.GAUTH_CLIENT_EMAIL}}
      GAUTH_CLIENT_ID: ${{secrets.GAUTH_CLIENT_ID}}
      GAUTH_AUTH_URI: ${{secrets.GAUTH_AUTH_URI}}
      GAUTH_TOKEN_URI: ${{secrets.GAUTH_TOKEN_URI}}
      GAUTH_AUTH_PROVIDER_X509_CERT_URL: ${{secrets.GAUTH_AUTH_PROVIDER_X509_CERT_URL}}
      GAUTH_CLIENT_X509_CERT_URL: ${{secrets.GAUTH_CLIENT_X509_CERT_URL}}
      GDRIVE_OUTCOME: ${{secrets.GDRIVE_OUTCOME}}
      GDRIVE_GENERAL: ${{secrets.GDRIVE_GENERAL}}
      GDRIVE_DOCUMENTS: ${{secrets.GDRIVE_DOCUMENTS}}
      GIT_BRANCH: draft/update_from_gdrive-curator
    steps:
      - name: create github app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1   
      - name: Checkout output in data repo
        uses: actions/checkout@v3
        with:
          repository: core-curriculum/data
          ref: ${{env.GIT_BRANCH}}
          token: ${{ steps.app-token.outputs.token }}
          path: output_in_github
          fetch-depth: 1  
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: download sheets and make output
        run: make
      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo' # タイムゾーン指定
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name: commit and push
        run: |
          cd output_in_github
          git add -N . # 新規ファイルを含める
          if ! git diff --exit-code --quiet
          then
            echo change ditected update reposistory
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Updated from gdrive-curator(${{ env.CURRENT_DATETIME }})"
            git push origin ${{env.GIT_BRANCH}}
          else
            echo no change
          fi

